<?php 
/**
 * ZF2 Buch Kapitel 5
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 5.5 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 5.5</h1>
<h3>Beispiel für den Einsatz des <code>SharedEventManager</code></h3>
<pre>
&lt;?php 
// setup autoloading
require_once LUIGI_ROOT . '/vendor/autoload.php';

// configure Autoloader
$loader = new Zend\Loader\StandardAutoloader();
$loader->registerNamespace('Pizza', LUIGI_ROOT . '/module/Pizza/src/Pizza');
$loader->register();

// namespaces
use Zend\EventManager\EventManager;
use Zend\EventManager\SharedEventManager;
use Pizza\Listener\OrderListener;
use Pizza\Model\Order;
use Pizza\Service\OrderService;

// configure shared manager
$sharedEventManager = new SharedEventManager();
$sharedEventManager->attach('Pizza\Service\OrderService', 'postOrder', function ($e) {
    echo "shared postOrder&lt;br /&gt;";
}, 250);

// configure event manager
$eventManager = new EventManager();
$eventManager->setSharedManager($sharedEventManager);
$eventManager->attachAggregate(new OrderListener(), 100);

// configure order service
$orderService = new OrderService();
$orderService->setEventManager($eventManager);

// create order
$order = new Order();
$order->customer = 'Rainer Zufall';
$order->items    = array(
    'PizzaSalami',
    'PizzaHawaii',
);

// save order
$orderService->saveOrder($order);
</pre>
<h3>Ausgabe</h3>
<pre>
<?php 
// namespaces
use Zend\EventManager\EventManager;
use Zend\EventManager\SharedEventManager;
use Pizza\Listener\OrderListener;
use Pizza\Model\Order;
use Pizza\Service\OrderService;

// configure shared manager
$sharedEventManager = new SharedEventManager();
$sharedEventManager->attach('Pizza\Service\OrderService', 'postOrder', function ($e) {
    echo "shared postOrder<br />";
}, 250);

// configure event manager
$eventManager = new EventManager();
$eventManager->setSharedManager($sharedEventManager);
$eventManager->attachAggregate(new OrderListener(), 100);

// configure order service
$orderService = new OrderService();
$orderService->setEventManager($eventManager);

// create order
$order = new Order();
$order->customer = 'Rainer Zufall';
$order->items    = array(
    'PizzaSalami',
    'PizzaHawaii',
);

// save order
$orderService->saveOrder($order);
?>
</pre>
</div>
</div>
