<?php 
/**
 * ZF2 Buch Kapitel 5
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 5</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing0501">Listing 5.1</a></td>
<td>Order Service implementiert <code>EventManagerAwareInterface</code></td>
</tr>
<tr>
<td><a href="/listing/listing0502">Listing 5.2</a></td>
<td>Konfiguration des Event-Managers mit Closure-Funktionen</td>
</tr>
<tr>
<td><a href="/listing/listing0503">Listing 5.3</a></td>
<td>OrderListener implementiert <code>ListenerAggregateInterface</code></td>
</tr>
<tr>
<td><a href="/listing/listing0504">Listing 5.4</a></td>
<td>Konfiguration des Event-Managers mit Listener-Klassen</td>
</tr>
<tr>
<td><a href="/listing/listing0505">Listing 5.5</a></td>
<td>Beispiel für den Einsatz des <code>SharedEventManager</code></td>
</tr>
</tbody>
</table>
